/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package helloworld;

import java.util.concurrent.ExecutionException;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws ExecutionException, InterruptedException {

        NewOrder newOrder = new NewOrder();

        newOrder.name();
    }
}
